In [208]:
#importa as bibliotecas
import pandas as pd
import numpy as np
import os
import datetime
from functools import reduce

In [209]:
#Abre o Fase atual
df = pd.read_excel("C:\\Users\\WIN10\\Documents\\Mont seguro\\Relatorio_Comercial\\Fase Atual.xlsx")

#Abre o Ganhos
df2 = pd.read_excel("C:\\Users\\WIN10\\Documents\\Mont seguro\\Relatorio_Comercial\\Ganhos.xlsx")

#Abre o Negociação
df3 = pd.read_csv("C:\\Users\\WIN10\\Documents\\Mont seguro\\Automação\\Relatorio_Comercial\\dados\\Negociação.csv", encoding='latin-1')

In [210]:
def preprocess_dataframe(df):
    # cria um objeto que convete string em datetime
    def extract_month(date_string):
        date_obj = datetime.datetime.strptime(date_string, '%Y-%m-%d %H:%M:%S.%f')
        return date_obj.month

    # cria um objeto que convete string em datetime
    def extract_year(date_string):
        date_obj = datetime.datetime.strptime(date_string, '%Y-%m-%d %H:%M:%S.%f')
        return date_obj.year

    # cria uma nova coluna 'numero do mês' baseada na coluna 'Previsão de Pagamento'
    df['numero do mês'] = df['Previsão de Pagamento'].dropna().apply(extract_month)
    # cria uma nova coluna 'numero do ano' baseada na coluna 'Previsão de Pagamento'
    df['numero do ano'] = df['Previsão de Pagamento'].dropna().apply(extract_year)

    #transforma numeros nan em -1 inteiro
    df['numero do mês'] = np.nan_to_num(df['numero do mês'], nan=-1).astype(int)

    df['numero do ano'] = np.nan_to_num(df['numero do ano'], nan=-1).astype(int)
    
    #tira o primeiro ponto dos numero, depois troca a virgula por ponto e transforma string em float
    if df['Valor'].dtype == 'object':
        df['Valor'] = df['Valor'].str.replace('.', '').str.replace(',', '.').astype(float)

    
    return df

In [211]:
#aplica as modificações nos DataFrames

df = preprocess_dataframe(df)
df2 = preprocess_dataframe(df2)
df3 = preprocess_dataframe(df3)

C:\Users\WIN10\AppData\Local\Temp\ipykernel_3388\3509542288.py:24: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Valor'] = df['Valor'].str.replace('.', '').str.replace(',', '.').astype(float)
C:\Users\WIN10\AppData\Local\Temp\ipykernel_3388\3509542288.py:24: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Valor'] = df['Valor'].str.replace('.', '').str.replace(',', '.').astype(float)

In [212]:
#cria filtro previsão proximo mes
filtro_proximo = ((df['numero do mês'] == datetime.datetime.now().month +1) & 
          (df['Fase atual'].isin(['Análise', 'Pagamento'])))



# cria filtro previsão esse mês
filtro_mes = ((df['numero do mês'] == datetime.datetime.now().month) | 
              (df['Previsão de Pagamento'].isna() &
               df['Fase atual'].isin(['Análise', 'Pagamento'])))


#cria filtro implantados
filtro_implantados = ((df2['numero do mês'] == datetime.datetime.now().month ) & 
                      (df2['numero do ano'] == datetime.datetime.now().year ))


#cria filtro pagamento

filtro_pagamentos = (df['Fase atual'].isin(['Pagamento']))



#cria filtro analise
filtro_analise = (df['Fase atual'].isin(['Análise']))


#cria filtro Documentação
filtro_documentacao = (df['Fase atual'].isin(['Documentação']))

#cria filtro fallow-up
filtro_follow_up = (df['Fase atual'].isin(['Follow Up']))

#cria filtro Documentação para filtros
filtro_documentacao2 = (df['Fase atual'].isin(['Documentação']))

In [213]:
newdf1 = filtro_proximo.to_frame(name='previsão proximo mes')
newdf2 = filtro_mes.to_frame(name='previsão esse mes')
newdf3 = filtro_implantados.to_frame(name='implantados')
newdf4 = filtro_pagamentos.to_frame(name='pagamento')
newdf5 = filtro_analise.to_frame(name='analise')
newdf6 = filtro_documentacao2.to_frame(name='Documentação')
newdf7 = filtro_follow_up.to_frame(name='fallow-up')

In [214]:
df3['contagem'] = df3['Responsável']
df['contagem'] = df['Responsável']

In [215]:
def agrupa_e_soma(df, filtro, coluna_valor, nome_coluna):
    df_agrupado = df[filtro].groupby(['Responsável'])[coluna_valor].sum().reset_index()
    df_agrupado = df_agrupado.rename(columns={coluna_valor: nome_coluna})
    return df_agrupado

df_responsavel1 = agrupa_e_soma(df, filtro_proximo, 'Valor', 'previsão proximo mês')
df_responsavel2 = agrupa_e_soma(df, filtro_mes, 'Valor', 'previsão esse mês')
df_responsavel3 = agrupa_e_soma(df2, filtro_implantados, 'Valor', 'implantados')
df_responsavel4 = agrupa_e_soma(df, filtro_pagamentos, 'Valor', 'pagamento')
df_responsavel5 = agrupa_e_soma(df, filtro_analise, 'Valor', 'análise')
df_responsavel6 = agrupa_e_soma(df, filtro_documentacao, 'Valor', 'documentação')
df_responsavel7 = df[filtro_follow_up].groupby(['Responsável'])['contagem'].count().reset_index().rename(columns={'contagem': 'Follow Up'})
df_responsavel8 = df3.groupby(['Responsável'])['contagem'].count().reset_index().rename(columns={'contagem': 'Em Negociação'})

In [216]:
#concatena todos os dataframes em um unico dataframe
dataframes = [df_responsavel2, df_responsavel3, df_responsavel4,
              df_responsavel5, df_responsavel6, df_responsavel7, df_responsavel8, df_responsavel1]

df_resultado = reduce(lambda df_left, df_right: pd.merge(df_left, df_right, on='Responsável', how='left'),
                      dataframes)

## -----------------------------------------------Ultima linha-----------------------------------------------------

In [217]:
dataframes = [newdf1, newdf2, newdf3, newdf4,
              newdf5, newdf6, newdf7]

df_filtros = pd.concat(dataframes, axis=1)

## -----------------------------------------------Ultima linha-----------------------------------------------------

In [218]:
def salvar_dataframe(dataframe, nome_arquivo):
    # Define o caminho onde o arquivo será salvo
    caminho_salvar = 'C:\\Users\\WIN10\\Documents\\Mont seguro\\Relatorio_Comercial'
    # Define o nome completo do arquivo, incluindo o caminho
    caminho_completo = os.path.join(caminho_salvar, nome_arquivo)
    # Salva o DataFrame em um arquivo Excel
    dataframe.to_excel(caminho_completo, index=False)

In [219]:
salvar_dataframe(df_resultado, 'Negociação.xlsx')

In [220]:
salvar_dataframe(df_filtros, 'Filtros.xlsx')

In [221]:
(df_filtros['Documentação'] ==True).sum()

6

In [222]:
teste = df[filtro_mes]
teste

,ID,Nome,Status,Fase atual,Valor,Dias sem interação,Atividades agendadas,Data prevista,Data da última interação,Contato relacionado - Nomes,...,Plataforma,Leads Resgatados por,Público,Anúncio,NOME (NEGÓCIO),Porte da empresa,Previsão de Pagamento,numero do mês,numero do ano,contagem
0,6550592,Leonardo Valverde,OPEN,Análise,1741.94,6,1,NaN,2023-02-24 17:49:02.0,Leonardo Valverde,...,Prospecção / Discadora,Islu,130720CP1 [FB/IG] [Públicos] [Empreendedores] ...,150620CP2C1A2 - Foto Sírio no topo,Leonardo Valverde,MEI,2023-03-10 00:00:00.0,3,2023,Giovanni
2,9128334,ODENILDO LISBOA /norma,OPEN,Pagamento,977.00,2,1,NaN,2023-02-28 18:14:38.0,eletrotecnica centro oeste,...,instagram,NaN,01 - VIDA DE LUXO,AD9 - CARD - BRADESCO DOURADO,eletrotecnica centro oeste,EIRELI,2023-03-03 00:00:00.0,3,2023,Giovanni
4,10179006,Leilane Da Silva Vieira Rodrigues,OPEN,Pagamento,1157.98,2,1,NaN,2023-02-28 10:31:14.0,Leilane Da Silva Vieira Rodrigues,...,instagram,Sammy,002 - LOOKALIKE 1% BSB,AD9 - CARD - BRADESCO DOURADO  Cópia,Leilane Da Silva Vieira Rodrigues,MEI,2023-03-06 00:00:00.0,3,2023,Giovanni
9,18202060,Souza,OPEN,Análise,2621.44,6,2,NaN,2023-02-24 15:59:04.0,Souza,...,facebook,NaN,[P03] [INTERESSES] [BENS DE LUXO + VIAJANTES F...,AD 03 | IMG | UNIMED,Souza,EIRELI,2023-03-20 00:00:00.0,3,2023,Vitória Monteiro
12,18416808,Júlia Flávia,OPEN,Pagamento,1552.50,8,1,NaN,2023-02-22 14:41:57.0,Júlia Flávia,...,instagram,NaN,[P05] [INTERESSES] [PLANO DE SAÚDE],AD 03 | IMG | LTDA - CAIXINHA BRADESCO,Júlia Flávia,MEI,2023-03-07 00:00:00.0,3,2023,Hiltom
13,18502568,Alex Jessica,OPEN,Análise,44.99,6,1,NaN,2023-02-24 14:27:43.0,Alex Jessica,...,facebook,NaN,[P04] [ADVOGADOS],AD 04 | IMAGEM | NOVO CARTÕES BRADESCO,Alex Jessica,ME,NaN,-1,-1,Vitória Monteiro
15,19079759,Priscila Lana,OPEN,Análise,3072.86,1,1,NaN,2023-03-01 14:56:34.0,Priscila Lana,...,instagram,NaN,[P05] [INTERESSES] [PLANO DE SAÚDE],AD 03 | IMG | LTDA - CAIXINHA BRADESCO,NaN,MEI,2023-03-10 00:00:00.0,3,2023,Hiltom
17,19131758,Por Shari Biller [DUPLICADO],OPEN,Análise,3601.84,1,1,NaN,2023-03-01 17:13:52.0,Por Shari Biller,...,instagram,NaN,[P02] [INTERESSES] [ABERTO] [Plano de Saúde],AD 02 | IMG | NOVO BRADESCO (Melhor Plano),NaN,LIMITADA-LTDA,2023-03-10 00:00:00.0,3,2023,Hiltom
20,19449619,Fred Alexandre,OPEN,Pagamento,781.56,7,1,NaN,2023-02-23 18:40:36.0,Fred Alexandre,...,instagram,NaN,[P04] [ADVOGADOS],AD 03 | IMG | LTDA - CAIXINHA BRADESCO,NaN,MEI,2023-03-01 00:00:00.0,3,2023,Vitória Monteiro
42,20482397,Negócio isabela bianor,OPEN,Análise,856.00,2,1,NaN,2023-02-28 18:42:03.0,isabela bianor,...,indicaçao - closer,NaN,NaN,NaN,NaN,NaN,2023-03-10 00:00:00.0,3,2023,Giovanni
44,20591294,Beatriz Hauffe,OPEN,Pagamento,819.27,1,1,NaN,2023-03-01 15:50:27.0,Beatriz Hauffe,...,instagram,NaN,[P01] [BM RESERVA] [INTERESSES] [PLANO DE SAÚDE],AD 01 | IMG | LTDA - CAIXINHA BRADESCO VERMELHO,NaN,LIMITADA-LTDA,2023-03-01 00:00:00.0,3,2023,Hiltom
45,20665975,Eliane Volcov,OPEN,Pagamento,560.66,15,1,NaN,2023-02-15 11:02:29.0,Eliane Volcov,...,disparo em massa whatsapp,NaN,NaN,NaN,NaN,NaN,2023-03-06 00:00:00.0,3,2023,Hiltom
55,21022025,Negócio Tatiane Menezes,OPEN,Pagamento,2507.00,2,1,NaN,2023-02-28 15:50:52.0,tatiane menezes,...,disparo em massa whatsapp,Islu,NaN,NaN,NaN,MEI,2023-03-02 00:00:00.0,3,2023,Giovanni
60,21352050,Anna,OPEN,Pagamento,1013.41,7,1,NaN,2023-02-23 12:25:24.0,Anna - ind. Hiltom,...,indicaçao - closer,NaN,NaN,Weslayne,NaN,NaN,2023-03-08 00:00:00.0,3,2023,Hiltom
61,21391254,LUIZ ROLIM,OPEN,Análise,1577.91,6,1,NaN,2023-02-24 12:33:59.0,Luiz Rolim,...,amigo/conhecido (network),NaN,NaN,NaN,NaN,NaN,2023-03-01 00:00:00.0,3,2023,Vitória Monteiro
65,21487353,SAUDEMAIS,OPEN,Análise,2313.83,6,1,NaN,2023-02-24 15:53:50.0,"Edy, empresa do Luiz",...,amigo/conhecido (network),NaN,NaN,NaN,NaN,NaN,NaN,-1,-1,Vitória Monteiro
66,21492236,Sálua Arruda | Fisioterapia,OPEN,Análise,593.54,1,1,NaN,2023-03-01 14:53:08.0,SÃ¡lua Arruda | Fisioterapia,...,instagram,NaN,[P01] [BM RESERVA] [INTERESSES] [PLANO DE SAÚDE],AD 01 | IMG | LTDA - CAIXINHA BRADESCO VERMELHO,NaN,MEI,2023-03-10 00:00:00.0,3,2023,Hiltom
68,21592599,CESAR MOURA SANTANNA [DUPLICADO],OPEN,Pagamento,808.81,0,1,NaN,2023-03-02 11:21:42.0,Cesar Moura Sant'Anna,...,GOOGLE- Formulario,NaN,NaN,NaN,NaN,ME,2023-03-10 00:00:00.0,3,2023,Hiltom

In [223]:
teste.loc[df2['Responsável'] == 'Vitória Monteiro']

,ID,Nome,Status,Fase atual,Valor,Dias sem interação,Atividades agendadas,Data prevista,Data da última interação,Contato relacionado - Nomes,...,Plataforma,Leads Resgatados por,Público,Anúncio,NOME (NEGÓCIO),Porte da empresa,Previsão de Pagamento,numero do mês,numero do ano,contagem
55,21022025,Negócio Tatiane Menezes,OPEN,Pagamento,2507.00,2,1,NaN,2023-02-28 15:50:52.0,tatiane menezes,...,disparo em massa whatsapp,Islu,NaN,NaN,NaN,MEI,2023-03-02 00:00:00.0,3,2023,Giovanni
61,21391254,LUIZ ROLIM,OPEN,Análise,1577.91,6,1,NaN,2023-02-24 12:33:59.0,Luiz Rolim,...,amigo/conhecido (network),NaN,NaN,NaN,NaN,NaN,2023-03-01 00:00:00.0,3,2023,Vitória Monteiro

In [224]:
df2[filtro_implantados]

,ID,Nome,Status,Fase atual,Valor,Dias sem interação,Atividades agendadas,Data prevista,Data da última interação,Contato relacionado - Nomes,...,Origem,Plataforma,Leads Resgatados por,Público,Anúncio,Possui Plano,Porte da empresa,Previsão de Pagamento,numero do mês,numero do ano
498,21131542,Bianka Campos [DUPLICADO],WON,Pagamento,1076.9,1,0,NaN,2023-03-01 09:22:02.0,Bianka Campos,...,NaN,instagram,NaN,[P01] [BM RESERVA] [INTERESSES] [PLANO DE SAÚDE],AD 01 | IMG | LTDA - CAIXINHA BRADESCO VERMELHO,NaN,MEI,2023-03-01 00:00:00.0,3,2023